[package]
name = "kunjika"
version = "0.0.1"
authors = ["Shiv Shankar Dayal <shivshankar.dayal@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# https://docs.rs/vergen/4.1.0/vergen/
[build-dependencies]
vergen = { version = "9.0.0-beta.1" }

[features]
default = ["postgres"]
postgres = ["sqlx/postgres"]

[dependencies.sqlx]
version = "0.7.3"
default-features = false
features = ["macros", "chrono", "uuid", "json", "time", "runtime-tokio"]
# git = "https://github.com/launchbadge/sqlx"
# path = "../sqlx"

[dependencies]
ntex = { version = "2.3.0", features = ["tokio", "cookie", "compress"] }
ntex-cors = { version = "2.0.0" }
clap = { version = "4.5.16", features = ["derive"] }
lettre = { version = "0.11.8", features = [
    "tokio1-native-tls",
    "hostname",
    "builder",
] }
nonblock-logger = { version = "0.2.2", default-features = false, features = [
    "color",
    "dbg",
] }
uuid = { version = "1.10.0", features = ["serde", "v4"] }
chrono = { version = "0.4.38", features = ["serde"] }
rust_decimal = { version = "1.36.0", features = ["serde-float"] }
validator = { version = "0.18.1", features = ["derive"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_qs = "0.13.0"
serde_json = "1.0.127"
json5 = "0.4.1"
rust-argon2 = "2.1.0"
ring = "0.17.8"
rand = "0.8.5"
hex = "0.4.3"
jsonwebtoken = "9.3.0"
lazy_static = "1.5.0"
futures = "0.3.30"
thiserror = "1.0.63"
anyhow = "1.0.86"
url = "2.5.2"
itsdangerous = "0.4.1"
num_cpus = "1.16.0"
cargo-watch = "8.4.0"
cookie = "0.18.1"
rust-analyzer = "0.0.1"
async-trait = "0.1.82"
mobc = "0.8.4"
mobc-redis = "0.8.2"
base64 = "0.22.1"
md5 = "0.7.0"
ntex-multipart = "2.0.0"
ntex-files = "2.0.0"
nix = "0.29.0"
